### ISSUE TITLE
Siempre subir el proyecto excto que crea el IDE de desarrollo

### ISSUE THREAD

**Issue by yosbel-penate** [KevinPinoDelSol/Tareas-Evaluativas-DPOO#2]
Siembre dar push a toda la carpeta del proyecto que crea el IDE java y no subir solo los archivos si no toda la extructura

**Comment by yosbel-penate** [comment]
probablemente si sube cosas que no hacen falta deberas dar un archivo de exclusion a git que le dice que tipos de archivos no debe subir, se puede encontrar en internet para cada ide

**Comment by KevinPinoDelSol** [comment]
> Siembre dar push a toda la carpeta del proyecto que crea el IDE java y no subir solo los archivos si no toda la extructura

Eso fue lo que hice.

**Comment by KevinPinoDelSol** [comment]
> probablemente si sube cosas que no hacen falta deberas dar un archivo de exclusion a git que le dice que tipos de archivos no debe subir, se puede encontrar en internet para cada ide

Si no me equivoco, me lo sacó automático. Pero no me fijé bien.
