### ISSUE TITLE
Ya completado

### ISSUE THREAD

**Issue by KevinPinoDelSol** [KevinPinoDelSol/Tareas-Evaluativas-DPOO#4]
@yosbel-penate recuerde que yo ya entregué la tarea. Lo digo para que me ponga la tarea como hecha en el proyecto de Curso de ingeniería.

**Comment by yosbel-penate** [comment]
Aún no le has adicionado Exception  al final del nombre de cada clase

**Comment by KevinPinoDelSol** [comment]
@yosbel-penate puede volver a mirar, ya le cambié los nombres.

**Comment by yosbel-penate** [comment]
Muy bien tiene 5.
